cartographme/config/routes.rb
Rails.application.routes.draw do
  
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root 'home#index'
  get 'home/index'
  post 'key_location/new'
  post 'key_location/assign'
  get  'key_location/destroy'
  delete 'key_location/destroy'
  
  get 'sessions/new'
  get 'users/new'
  get 'users/following'
  
  post 'home/search_friends'
  post 'users/profile'
  post 'users/following'
  delete 'users/destroy'
  
  post 'sessions/user_params'
  
  delete 'relationships/destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions
  resources :relationships, only: [:create, :destroy]
  
  match '/signup', to: 'users#new', via: :get
  match '/login', to: 'sessions#new', via: :get
  match '/logout', to: 'sessions#destroy', via: :delete

end

cartographme/app/models/user.rb
class User < ActiveRecord::Base
  cattr_accessor :current_user
  has_secure_password
  has_and_belongs_to_many :key_locations
  
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save {|user| user.email=user.email.downcase}
  before_save :create_session_token
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true
    
  def self.find_by_email(*args) 
    super
  end
  
  #follow a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  
  #unfollow a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  #returns true if the current user is following the other user
  def following?(other_user)
    following.include?(other_user)
  end
  
  private
    def create_session_token
      self.session_token = SecureRandom.urlsafe_base64
    end
    
    def self.search(search)
      if search
        where("name LIKE ?", "%#{search.downcase}%")
      else
        all
      end
    end
end

cartographme/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_current_user, :only=> ['show', 'edit', 'update', 'delete']

  def index
    @users = User.search( params[:search])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    puts User
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Sign up successful! Welcome #{@user.email}"
      redirect_to login_path
    else
      render 'new'
    end  
  end
  
  #private
  # Use callbacks to share common setup or constraints between actions.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def profile
  end
end

cartographme/app/helpers/users_helper.rb
module UsersHelper

end

cartographme/app/views/users/follow_page.html.haml
%h1 Users Following

cartographme/app/views/users/index.html.haml
%link(rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css")
%script(src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js")
%script(src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js")

%h1 Users
%h2
  = form_tag users_path, :method => 'get', :id => 'users_search'  do
    %p
      = text_field_tag :search, params[:search], placeholder: "Search Users"
      = button_tag type: "submit", :name => nil, :class => "button" do
        Search
  
  - @users.each do |user|
    %p
      = user.name
      = button_to user, :method => 'get',:class => "button" do
        see profile
        %span(class="glyphicon glyphicon-user")

cartographme/app/views/users/new.html.haml
%link(rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css")
%script(src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js")
%script(src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js")
%h2
  %p
  = link_to 'Log-in to Cartographme', login_path, :class => "btn btn-link"

%h1 Sign-up 
#outer
  -unless @user ==nil
    -if @user.errors.any?
      %ul
      -@user.errors.full_messages.each do |msg|
        %li #{msg}

#outer
  = form_tag users_path, :id=>'signup_form', :method=> 'post' do
  
    = label :user, :name, 'Name'
    %br
    = text_field :user, 'name'
  
    %br
    = label :user, :email, 'Email'
    %br
    = text_field :user, 'email'
  
    %br
    = label :user, :password, 'Password'
    %br
    = password_field :user, 'password'
  
    %br
    = label :user, :password_confirmation, 'Password confirmation'
    %br
    = password_field :user, 'password_confirmation'
    %h2
      = button_tag type: "submit", :name => nil, :class => "button" do
        Create my account
        %span(class="glyphicon glyphicon-new-window")
      

cartographme/app/views/users/show.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<h1> User profile for <%= @user.name %> </h1> 
<h2>
    <u1>
      <div class="dropdown">
      <% if @current_user != @user then %>
        <% if @current_user.following.include?(@user) then %>
          <%= button_to relationship_path(:user_id => @user.id), :method => :delete, :id => 'unfollow_button', :class => "btn btn-warning" do %>
            Unfollow
            <span class="glyphicon glyphicon-minus-sign"> </span>
          <% end %>
        <% else %>
          <%= button_to relationships_path(:followed_id => @user.id), :method => :create, :id => 'follow_button', :class => "btn btn-primary" do %>
            Follow
            <span class="glyphicon glyphicon-plus-sign"> </span>
          <% end %>
          <% end %>
      <% else %>
          <button type="button" class= "btn btn-info">
          My Profile <span class="glyphicon glyphicon-star"> </span>
          </button>
      <% end %>
      </div>
    </u1>
  </h2>
<h2>
  <ul>
      <div class="dropdown">
        <button class="dropbtn"> <span class="glyphicon glyphicon-user"> </span> User Info</button>
        <div class="dropdown-content">
          <a>
              <strong>Name: </strong> <%=@user.name %>
          </a>
          <a>
              <strong>Email: </strong> <%=@user.email %>
          </a>
          </div>
      </div>
      
      <div class="dropdown">
        <button class="dropbtn"> <span class="glyphicon glyphicon-eye-open"> </span> Following (<%= @user.following.count %>)</button>
        <div class="dropdown-content">
          <% array = @user.following%>
          <% array = array.uniq%>
          <% if array.length > 3 %>
          <div class="myBox">
              <% if array.empty? == true then %>
                <a><%= "none" %></a>
              <% else %>
                <% array.each do |follow|%>
                  <p><%= link_to "#{follow.name}", user_path(id: follow.id) %></p>
                  
                <% end %>
              <% end %>
          </div>
          <% else %>
            <% if array.empty? == true then %>
                <a><%= "none" %></a>
              <% else %>
                <% array.each do |follow|%>
                  <p><%= link_to "#{follow.name}", user_path(id: follow.id) %></p>
                <% end %>
              <% end %>
          <% end %>
        </div>
      </div>
      
      <div class="dropdown">
        <button class="dropbtn"> <span class="glyphicon glyphicon-sunglasses"> </span> Followers (<%= @user.followers.count %>)</button>
        <div class="dropdown-content">
          
          <% array = @user.followers%>
          <% array = array.uniq%>
          <% if array.length > 3 %>
          <div class="myBox">
              <% if array.empty? == true then %>
                <a><%= "none" %></a>
              <% else %>
                <% array.each do |follow|%>
                  <p><%= link_to "#{follow.name}", user_path(id: follow.id)  %></p>
                <% end %>
              <% end %>
          </div>
          <% else %>
            <% if array.empty? == true then %>
                <a><%= "none" %></a>
              <% else %>
                <% array.each do |follow|%>
                  <p><%= link_to "#{follow.name}", user_path(id: follow.id)  %></p>
                <% end %>
              <% end %>
          <% end %>
        </div>
      </div>
         <% array = @user.key_locations%>
          <% array = array.uniq%>
          
      <div class="dropdown">
        <button class="dropbtn" id="drop"> <span class="glyphicon glyphicon-road"> </span> 
        Locations visited (<%= array.length %>)</button>
        <div class="dropdown-content">
          
          <% if array.length > 2 %>
          <div class="myBox">
              <% if array.empty? == true then %>
                <a><%= "none" %></a>
              <% else %>
                <% array.each do |location|%>
                    <a><%= location.name %></a>
                    <i><%= location.description %></i>
                <% end %>
              <% end %>
          </div>
          <% else %>
            <% if array.empty? == true then %>
                <a><%= "none" %></a>
              <% else %>
                <% array.each do |location|%>
                    <a><%= location.name %></a>
                    <i><%= location.description %></i>
                <% end %>
              <% end %>
          <% end %>
        </div>
      </div>
      
      <% array = @user.key_locations%>
          <% array = array.uniq%>
          <% records = 0%>
          <% no_rec = false%>
          
          <% array.each do |location|%>
              <% if location.email == @user.email %>
               <% no_rec = true%>
                <% records = records +1 %>
              <% end %>
          <% end %>
      <div class="dropdown">
        <button class="dropbtn" id="drop1"> <span class="glyphicon glyphicon-map-marker"> </span>
        Recommended Places (<%= records %>)</button>
        <div class="dropdown-content">
          
          
          <% if records > 2 %>
          <div class="myBox">
              <% array.each do |location|%>
                  <% if location.email == @user.email %>
                    <a><%= location.name %></a>
                    <i><%= location.description %></i>
                  <% end %>
              <% end %>
              <% if no_rec == false%>
                <a><%= "none" %></a>
              <% end %>
          </div>
          <% else %>
            <% array.each do |location|%>
                  <% if location.email == @user.email %>
                    <% no_rec = true%>
                    <a><%= location.name %></a>
                    <i><%= location.description %></i>
                  <% end %>
              <% end %>
              <% if no_rec == false%>
                <a><%= "none" %></a>
              <% end %>
          <% end %>
        </div>
      </div>
    </u1>
  </h2>