cartographme/config/routes.rb
Rails.application.routes.draw do
  
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root 'home#index'
  get 'home/index'
  post 'key_location/new'
  post 'key_location/assign'
  get  'key_location/destroy'
  delete 'key_location/destroy'
  
  get 'sessions/new'
  get 'users/new'
  get 'users/following'
  
  post 'home/search_friends'
  post 'users/profile'
  post 'users/following'
  delete 'users/destroy'
  
  post 'sessions/user_params'
  
  delete 'relationships/destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions
  resources :relationships, only: [:create, :destroy]
  
  match '/signup', to: 'users#new', via: :get
  match '/login', to: 'sessions#new', via: :get
  match '/logout', to: 'sessions#destroy', via: :delete

end

cartographme/app/controllers/home_controller.rb
#Controller for main page not asscociated with any 1 model
class HomeController < ApplicationController
  before_filter :set_current_user
  def index
    # Finds current user
    user = User.find_by session_token: session[:session_token]
    #adds test locations to all Markers will be from locations db when done
      @all_locations = KeyLocation.all
      @all_markers= Array.new
    if user != nil
      @visited_locations = user.key_locations
      @visited_locations.uniq!
    end 
      @all_locations.each do |loc|
        if user != nil
          if loc.email == user.email or loc.email == 'admin'
            if( @visited_locations.include?(loc) )
              @marker_icon =  ActionController::Base.helpers.image_url('green_dot.png')
              info_content = loc.getVisitedInfoString()
            else
              @marker_icon =  ActionController::Base.helpers.image_url('red_dot.png')
              info_content = loc.getInfoString()
            end
            marker={
              :lat => loc.lat,
              :lng => loc.lng,
              :infowindow => info_content,
              :picture => { :url=>@marker_icon, :width => 20, :height => 20 },
            }
            @all_markers.push(marker)
          end
        end
        
      end
    gon.allMarkers = @all_markers
    gon.markerVisitedIcon = { :url=> ActionController::Base.helpers.image_url('green_dot.png'), :width => 20, :height => 20 }
    
  end
  
end

cartographme/app/helpers/home_helper.rb
module HomeHelper
end

cartographme/app/views/home/index.html.haml
/ Home page

%link(rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css")
%script(src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js")
%script(src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js")


#outer
  -if @current_user
    .inner
      = button_to @current_user, :method => :get, :id => 'profile_button', :class => "button" do
        My Profile
        %span(class="glyphicon glyphicon-star")
    .inner
      = button_to users_path, :method => :get, :id => 'search_button', :class => "button" do
        Search Users
        %span(class="glyphicon glyphicon-search")
    .inner
      = button_to logout_path , :method => :delete , :id => 'logout', :class => "button" do
        Logout
        %span(class="glyphicon glyphicon-log-out")
    #div{:class => "card"}
      #map{:style => "width:50; height:550px;"}
  -else
    %h2
      = button_to login_path , :method => :get, :id => 'signuplogin', :class => "button" do
        Sign up/Login
        %span(class="glyphicon glyphicon-log-in")
  